In [ ]:
import numpy as np
a= np.arange(10)
%timeit a**2  


473 ns ± 16.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
import numpy as np 
a= np.array([0,1,2,3,4,5,6])
a 


array([ True, False,  True, False,  True, False,  True])

In [17]:
import numpy as np
a= np.random.randint(0,20,15) # print random 15 number from 0 to 20
a 


array([12,  6,  6, 14,  4, 11, 13, 14,  2, 18,  9, 19,  6, 12,  4],
      dtype=int32)

In [18]:
even= (a % 2 == 0)
even 

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True, False, False,  True,  True,  True])

In [19]:
extract_from_a = a[even]
extract_from_a

array([12,  6,  6, 14,  4, 14,  2, 18,  6, 12,  4], dtype=int32)

In [ ]:
a[even]= -1 # it will replace the even numbers with -1 
a 

array([-1, -1, -1, -1, -1, 11, 13, -1, -1, -1,  9, 19, -1, -1, -1],
      dtype=int32)

In [ ]:
a= np.arange(0,100,10) # it will create an array from 0 to 100 with gap of 10
a 

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# indexing is done with the help of a list, here the index whose value will be printed 
a[[2,5,9,1]]


array([20, 50, 90, 10])

In [29]:
a[[3,6]] = 100 # here we can assign value to the index 
a[[4]] = -300
a 

array([   0,   10,   20,  100, -300,   50,  100,   70,   80,   90])

In [ ]:
import numpy as np

In [ ]:
# ELEMENTWISE OPERATION

In [ ]:
#1. Basic Operations 

In [ ]:
a= np.array([1,2,3,4,5,6])   
a+1                             # adds +1 value to every element 

array([2, 3, 4, 5, 6, 7])

In [32]:
a**2

array([ 1,  4,  9, 16, 25, 36])

In [33]:
a//2

array([0, 1, 1, 2, 2, 3])

In [34]:
a-2 

array([-1,  0,  1,  2,  3,  4])

In [35]:
a%2

array([1, 0, 1, 0, 1, 0])

In [40]:
b= np.ones(6) + 1
a-b 

array([-1.,  0.,  1.,  2.,  3.,  4.])

In [41]:
a*b 

array([ 2.,  4.,  6.,  8., 10., 12.])

In [42]:
a+b 

array([3., 4., 5., 6., 7., 8.])

In [47]:
# MATRIX MULTIPLICATION 

c= np.diag([1,2,3,4,5])
print(c*c)
print("       OR             ")
print(c.dot(c)) 

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
       OR             
[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]


In [49]:
# COMPARISONS
a= np.array([1,2,3,4])
b= np.array([5,6,7,3])
a==b  

array([False, False, False, False])

In [50]:
a>b 

array([False, False, False,  True])

In [51]:
a<b 

array([ True,  True,  True, False])

In [ ]:
#ARRAY_WISE COMPARIOSN 
a= np.array([1,2,3,4,5])
b= np.array([6,4,2,8,9])     
c= np.array([1,2,3,4,5])
np.array_equal(a,b)

False

In [53]:
np.array_equal(a,c) 

True

In [54]:
# LOGICAL OPERATIONS 
A= np.array([0,1,0,1,0], dtype= bool)
B= np.array([1,0,0,1,1], dtype= bool)
np.logical_or(A,B)

array([ True,  True, False,  True,  True])

In [55]:
np.logical_and(A,B)

array([False, False, False,  True, False])

In [56]:
np.logical_not(A,B)

array([ True, False,  True, False,  True])

In [57]:
np.logical_xor(A,B) 

array([ True,  True,  True,  True,  True])

In [59]:
a= np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [60]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [61]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [62]:
np.log(a) 

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19744\1078742419.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [63]:
np.exp(a) 

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [67]:
a= np.arange(4)
a + np.array([1,2]) 

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [69]:
a= np.array([1,2,3,4])
np.sum(a) 

np.int64(10)

In [71]:
# sum by rowa and columns 
a= np.array([[1,2], [3,4]])
a 

array([[1, 2],
       [3, 4]])

In [ ]:
a.sum(axis=0)   #column first dimension 

array([4, 6])

In [ ]:
a.sum(axis=1)   #row first dimension 

array([3, 7])

In [ ]:
a= np.array([1,2,4,9,8,7])
a.min()

np.int64(9)

In [76]:
a.max()

np.int64(9)

In [77]:
a.argmin()  #gives index of min value 

np.int64(0)

In [78]:
a.argmax()  #gives index of max value 

np.int64(3)

In [ ]:
np.all([True,False,True]) # ek bhi false h to false return krega 

np.False_

In [ ]:
np.any([True, False, True, False, False, False])   # koi ek bhi value true to true return krega

np.True_

In [82]:
a= np.zeros([50,50])
np.any(a != 0)

np.False_

In [83]:
np.all(a==a)

np.True_

In [87]:
a= np.array([1,3,4,5])
b= np.array([3,4,5,6])
c= np.array([3,9,5,6])
((a<=b) & (b<=c)).all()

np.True_

In [2]:
import numpy as np
a= np.array([1,2,3,4])
b= np.array([[1,2,3],[4,5,6]])
a.mean() 

np.float64(2.5)

In [3]:
b.mean()

np.float64(3.5)

In [6]:
np.median(a)

np.float64(2.5)

In [7]:
np.median(b)

np.float64(3.5)

In [8]:
np.median(b, axis=-1)  #last axis 

array([2., 5.])

In [9]:
a.std()                   # full population standard deviation  

np.float64(1.118033988749895)

In [2]:
import numpy as np
data = np.loadtxt('populations.txt')

In [3]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [ ]:
year,hares,lynxes,carrots = data.T         #columns to variables , .T means transpose of a matrix
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [ ]:
# the mean population over time, 
# 1st shows as row and 2nd shows as column
population = data[:,1:]
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [ ]:
# standard deviation row-wise    = axis-1
# standard deviation column-wise    = axis-0
population.std(axis=0)

array([20897.90645809, 16254.59153691,  3322.50622558])

In [7]:
population.std(axis=1)

array([18176.23601177, 19614.67704439, 24668.33327703, 19225.21492439,
       10030.73055941,  9530.41913501,  9458.79954798, 12319.18106946,
       14923.434219  , 13472.52347888, 15759.51211879, 16967.22330456,
       18751.53327064, 23553.39088586,  5266.87763291, 13018.02169644,
       10757.4263754 , 14578.82787546, 14819.88154099, 13501.68713737,
       15873.31793363])

In [ ]:
# which species has the highest population each year 
np.argmax(population,axis=1)          #row-wise

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [4]:
a=np.tile(np.arange(0,40,10),(3,1))          #1(second argument) is shows number of tiles
print(a)
print("*************")
a=a.T
print(a)
a.shape

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
*************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


(4, 3)

In [6]:
import numpy as np
b=np.array([0,1,2])
b


array([0, 1, 2])

In [7]:
b.shape

(3,)

In [8]:
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [11]:
a=np.arange(0,40,10)
a.shape

(4,)

In [75]:
import numpy as np
b=np.array([0,1,2])
b

array([0, 1, 2])

In [91]:
b=b[:, np.newaxis]       #adds a new axis -> 2D array
b.shape

(3, 1, 1)

In [92]:
a=np.array([[1,2,3],[4,5,6]])
a.ravel()       #return a contiguous flattened array, A 1-D array

array([1, 2, 3, 4, 5, 6])

In [93]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [94]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [95]:
print(a.shape)

(2, 3)


In [96]:
b=a.ravel()
print(b)
b.shape

[1 2 3 4 5 6]


(6,)

In [104]:
b = b.reshape(2,3)
b

array([[100,   2,   3],
       [  4,   5,   6]])

In [105]:
b[0,0] = 100
a

array([[100,   2,   3],
       [  4,   5,   6]])

In [110]:
#reshape may also return a copy 
a=np.zeros((3,2))
b=a.T.reshape(3*2)
b[0]=50
a

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [111]:
b

array([50.,  0.,  0.,  0.,  0.,  0.])

In [120]:
z=np.array([1,2,3])
z

array([1, 2, 3])

In [121]:
z[:,np.newaxis]


array([[1],
       [2],
       [3]])

In [ ]:
a=np.arange(4*3*2)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [128]:
a = np.arange(4*3*2).reshape(4,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [130]:
a.shape

(4, 3, 2)

In [132]:
print(a[0,2,1])

5


In [ ]:
a=np.arange(4)
a.resize((8,))             #copy previous values and fill 0's in remaining places.
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [ ]:
b=a 
a.resize((4,))            #it does not possible, because large size does not convert into small size

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [136]:
# sorting along an axis 
a=np.array([[5,4,6],[2,3,2]])
b=np.sort(a,axis=1)
b

array([[4, 5, 6],
       [2, 2, 3]])

In [137]:
# in-place sort 
a.sort(axis=1)
a

array([[4, 5, 6],
       [2, 2, 3]])

In [ ]:
# sorting with fancy indexing 
a=np.array([4,3,1,2])
j=np.argsort(a)             #returns index of every element after the sorting
j

array([2, 3, 1, 0])

In [139]:
a[j]

array([1, 2, 3, 4])