In [ ]:
import numpy as np
a= np.arange(10)
%timeit a**2  


473 ns ± 16.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [ ]:
import numpy as np 
a= np.array([0,1,2,3,4,5,6])
a 


array([ True, False,  True, False,  True, False,  True])

In [17]:
import numpy as np
a= np.random.randint(0,20,15) # print random 15 number from 0 to 20
a 


array([12,  6,  6, 14,  4, 11, 13, 14,  2, 18,  9, 19,  6, 12,  4],
      dtype=int32)

In [18]:
even= (a % 2 == 0)
even 

array([ True,  True,  True,  True,  True, False, False,  True,  True,
        True, False, False,  True,  True,  True])

In [19]:
extract_from_a = a[even]
extract_from_a

array([12,  6,  6, 14,  4, 14,  2, 18,  6, 12,  4], dtype=int32)

In [ ]:
a[even]= -1 # it will replace the even numbers with -1 
a 

array([-1, -1, -1, -1, -1, 11, 13, -1, -1, -1,  9, 19, -1, -1, -1],
      dtype=int32)

In [ ]:
a= np.arange(0,100,10) # it will create an array from 0 to 100 with gap of 10
a 

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# indexing is done with the help of a list, here the index whose value will be printed 
a[[2,5,9,1]]


array([20, 50, 90, 10])

In [29]:
a[[3,6]] = 100 # here we can assign value to the index 
a[[4]] = -300
a 

array([   0,   10,   20,  100, -300,   50,  100,   70,   80,   90])

In [ ]:
import numpy as np

In [ ]:
# ELEMENTWISE OPERATION

In [ ]:
#1. Basic Operations 

In [ ]:
a= np.array([1,2,3,4,5,6])   
a+1                             # adds +1 value to every element 

array([2, 3, 4, 5, 6, 7])

In [32]:
a**2

array([ 1,  4,  9, 16, 25, 36])

In [33]:
a//2

array([0, 1, 1, 2, 2, 3])

In [34]:
a-2 

array([-1,  0,  1,  2,  3,  4])

In [35]:
a%2

array([1, 0, 1, 0, 1, 0])

In [40]:
b= np.ones(6) + 1
a-b 

array([-1.,  0.,  1.,  2.,  3.,  4.])

In [41]:
a*b 

array([ 2.,  4.,  6.,  8., 10., 12.])

In [42]:
a+b 

array([3., 4., 5., 6., 7., 8.])

In [47]:
# MATRIX MULTIPLICATION 

c= np.diag([1,2,3,4,5])
print(c*c)
print("       OR             ")
print(c.dot(c)) 

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
       OR             
[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]


In [49]:
# COMPARISONS
a= np.array([1,2,3,4])
b= np.array([5,6,7,3])
a==b  

array([False, False, False, False])

In [50]:
a>b 

array([False, False, False,  True])

In [51]:
a<b 

array([ True,  True,  True, False])

In [ ]:
#ARRAY_WISE COMPARIOSN 
a= np.array([1,2,3,4,5])
b= np.array([6,4,2,8,9])     
c= np.array([1,2,3,4,5])
np.array_equal(a,b)

False

In [53]:
np.array_equal(a,c) 

True

In [54]:
# LOGICAL OPERATIONS 
A= np.array([0,1,0,1,0], dtype= bool)
B= np.array([1,0,0,1,1], dtype= bool)
np.logical_or(A,B)

array([ True,  True, False,  True,  True])

In [55]:
np.logical_and(A,B)

array([False, False, False,  True, False])

In [56]:
np.logical_not(A,B)

array([ True, False,  True, False,  True])

In [57]:
np.logical_xor(A,B) 

array([ True,  True,  True,  True,  True])

In [59]:
a= np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [60]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [61]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [62]:
np.log(a) 

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_19744\1078742419.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [63]:
np.exp(a) 

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [67]:
a= np.arange(4)
a + np.array([1,2]) 

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [69]:
a= np.array([1,2,3,4])
np.sum(a) 

np.int64(10)

In [71]:
# sum by rowa and columns 
a= np.array([[1,2], [3,4]])
a 

array([[1, 2],
       [3, 4]])

In [ ]:
a.sum(axis=0)   #column first dimension 

array([4, 6])

In [ ]:
a.sum(axis=1)   #row first dimension 

array([3, 7])

In [ ]:
a= np.array([1,2,4,9,8,7])
a.min()

np.int64(9)

In [76]:
a.max()

np.int64(9)

In [77]:
a.argmin()  #gives index of min value 

np.int64(0)

In [78]:
a.argmax()  #gives index of max value 

np.int64(3)

In [ ]:
np.all([True,False,True]) # ek bhi false h to false return krega 

np.False_

In [80]:
np.any([True, False, True, False, False, False])   # koi ek bhi value true to true return krega

np.True_

In [82]:
a= np.zeros([50,50])
np.any(a != 0)

np.False_

In [83]:
np.all(a==a)

np.True_

In [87]:
a= np.array([1,3,4,5])
b= np.array([3,4,5,6])
c= np.array([3,9,5,6])
((a<=b) & (b<=c)).all()

np.True_

In [88]:
a= np.array([1,2,3,4])
b= np.array([[1,2,3],[4,5,6]])
a.mean() 

np.float64(2.5)

In [89]:
b.mean()

np.float64(3.5)

In [90]:
np.median(a)

np.float64(2.5)

In [91]:
np.median(b)

np.float64(3.5)

In [92]:
np.median(b, axis=-1)  #last axis 

array([2., 5.])

In [ ]:
a.std()                   # full population standard deviation  

np.float64(1.118033988749895)